services:
  backend:
    build: .\backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLIENT_URL=http://localhost:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: .\frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000/api
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: project-management-network


